### ISSUE TITLE
Check for supported version of runtime in shell before executing workflow

### ISSUE THREAD

**Issue by sanathkr** [awslabs/aws-lambda-builders#11]
**Description:**
Every workflow has to make sure it has a compatible version of Python/Node/NPM/PIP etc in the shell before processing. This is necessary to make sure customers are building in a version of programming language that is compatible with AWS Lambda runtime (ex: py3.6 vs py2.7 are incompatible). 

This is grunt work that could be abstracted into the `BaseWorkflow` similar to `BaseWorkflow.SUPPORTED_MANIFESTS`. This will also help us generate a standard error message on failure to satisfy prerequisites across all workflows.

**Comment by TheSriram** [comment]
This is addressed with Resolver and Validator features.
