### ISSUE TITLE
Build issues with pip 19.3

### ISSUE THREAD

**Issue by mvanbaak** [awslabs/aws-lambda-builders#131]
**Description:**

```sam build``` does not work with pip 19.3.
```
Building resource 'NotifyLowCreditsFunction'
Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'module' object is not callable
```

**Steps to reproduce the issue:**
1. activate virtual environment with python 3.7
2. make sure pip is the latest version ```pip install -U pip```
3. run ```sam build```

**Observed result:**
```
Building resource 'MyLambdaFunction'
Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: 'module' object is not callable
```
**Expected result:**
```
Building resource 'MyLambdaFunction'
Running PythonPipBuilder:ResolveDependencies
Running PythonPipBuilder:CopySource

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Package: sam package --s3-bucket <yourbucket>
```
**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

First noticed the issue during CI/CD builds.
These build run in a docker container using the ```python:3.7``` image.
Confirmed that the same error exists when using the lambci/lambda:build-python3.7 docker image.
Confirmed that the same error exists with python 3.7.4 on macos.

Downgrading pip with ```pip install 'pip==19.2.3'``` makes the build work again.

**Comment by TheSriram** [comment]
There is a fix in the works: https://github.com/awslabs/aws-lambda-builders/pull/132

**Comment by jfuss** [comment]
This was release both in aws-lambda-builders (v0.5.0) and SAM CLI (v0.23.0). 

Closing
