### ISSUE TITLE
Pip Workflow: Criptic error message why pip is not install in the python version

### ISSUE THREAD

**Issue by jfuss** [awslabs/aws-lambda-builders#135]
**Description:**

If the `import pip` fails during `python -c "import pip; print(pip.__version__)", we see an error `SAM CLI: Error: PythonPipBuilder:ResolveDependencies - invalid literal for int() with base 10: '' ` in SAM CLI. This is caused by trying to cast the output of `print(pip.__version__)` to an int. The works in most cases, but have seen it fail in python2.7 when the pip module is not found. Instead of giving this weird message back to customers, we should fail the workflow with a better message to customers on what is wrong (no pip found) and how to resolve (install pip into that python version).

**Comment by sriram-mv** [comment]
https://github.com/awslabs/aws-lambda-builders/pull/146

Closing, this is fixed and released.
